# Generated by Django 4.0.5 on 2022-06-18 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(default='lbscek123', max_length=16)),
                ('admission_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMS.student')),
            ],
        ),
    ]
