# Generated by Django 4.0.5 on 2022-06-19 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0002_remove_student_password_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('complaint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('complaint_desc', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('admission_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMS.student')),
                ('room_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_room_no', to='HMS.student')),
            ],
        ),
    ]
