# Generated by Django 4.0.5 on 2022-06-19 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0003_complaints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='room_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_room_no', to='HMS.student'),
        ),
    ]
