# Generated by Django 4.0.5 on 2022-06-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0004_alter_complaints_room_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='room_no',
            field=models.IntegerField(),
        ),
    ]
