# Generated by Django 4.0.5 on 2022-06-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0005_alter_complaints_room_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_no',
            field=models.IntegerField(default=0),
        ),
    ]
