# Generated by Django 4.0.5 on 2022-06-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0006_student_address_student_phone_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('designation', models.CharField(max_length=25)),
                ('phone_no', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='complaints',
            name='hostel',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
