# Generated by Django 4.0.5 on 2022-07-16 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0008_alter_student_admission_no_alter_student_phone_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='room_no',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='workers',
            name='phone_no',
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hostel', models.CharField(max_length=20)),
                ('out_time', models.DateTimeField()),
                ('in_time', models.DateTimeField(default='null')),
                ('mess_cut', models.BigIntegerField()),
                ('admission_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMS.student')),
            ],
        ),
    ]
