# Generated by Django 4.0.5 on 2022-07-16 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0009_alter_complaints_room_no_alter_workers_phone_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='admission_no',
            field=models.BigIntegerField(),
        ),
    ]
