# Generated by Django 4.0.5 on 2022-07-16 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0010_alter_movement_admission_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='admission_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMS.student'),
        ),
    ]
