# Generated by Django 4.0.5 on 2022-07-18 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0014_alter_movement_in_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='mess_cut',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
