# Generated by Django 4.0.5 on 2022-07-24 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0016_billinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Billinfo',
        ),
    ]
