# Generated by Django 4.0.5 on 2022-07-24 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0017_delete_billinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billinfo',
            fields=[
                ('bill_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('month', models.CharField(max_length=20)),
                ('mess_cut', models.BigIntegerField()),
                ('etablishment_charge', models.IntegerField()),
                ('mess_fee', models.IntegerField()),
                ('fine', models.IntegerField(default=0)),
                ('last_date', models.DateTimeField(null=True)),
                ('total', models.IntegerField()),
                ('admission_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMS.student')),
            ],
        ),
    ]
