# Generated by Django 4.0.5 on 2022-07-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0018_billinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinfo',
            name='hostel',
            field=models.CharField(default='MH1', max_length=10),
        ),
    ]
